name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: Asifkhan-akhan
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution snake"
          add: "dist/snake.svg"
